In [1]:
# @title Default title text
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:



# STEP 2: Import Required Libraries
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# STEP 3: Load Dataset
# Option 1: Directly from sklearn
iris = load_iris()
X = iris.data
y = iris.target
df = pd.DataFrame(X, columns=iris.feature_names)
df['species'] = y

# Option 2: Save dataset to Google Drive as CSV
save_path = '/content/drive/MyDrive/iris/Iris.csv'
df.to_csv(save_path, index=False)
print(f"✅ Dataset saved to Google Drive at: {save_path}")

# STEP 4: Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# STEP 5: Data Preprocessing (Scaling)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# STEP 6: Train Model (Logistic Regression)
model = LogisticRegression(max_iter=200)
model.fit(X_train, y_train)

# STEP 7: Make Predictions
y_pred = model.predict(X_test)

# STEP 8: Evaluate Model
accuracy = accuracy_score(y_test, y_pred)
print(" Model Accuracy:", accuracy)
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=iris.target_names))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

# STEP 9: Save Trained Model to Google Drive
import joblib
model_path = '/content/drive/MyDrive/iris/Iris.csv'
joblib.dump(model, model_path)
print(f"Trained model saved at: {model_path}")


✅ Dataset saved to Google Drive at: /content/drive/MyDrive/iris/Iris.csv
 Model Accuracy: 1.0

Classification Report:
               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30


Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Trained model saved at: /content/drive/MyDrive/iris/Iris.csv
